### PR TITLE
Use crystal-lib/clang.cr as libClang binding

### PR DESCRIPTION
**Pull request by olbat**
~~(I will rebase and remove the cherry-picked commit that adds support to Crystal 0.26 once we'll be sure the tests are passing)~~

### CODE REVIEW

**Comment by olbat** [comment]
One test is still failing.

I don't understand why ATM but unexposed structs are not [parsed](https://github.com/crystal-lang/crystal_lib/blob/master/src/crystal_lib/parser.cr#L224) the same way when using the _clang.cr_ library.

Someone may have an idea? (@ysbaddaden ?)

**Comment by ysbaddaden** [comment]
No idea, sorry :(

**Comment by olbat** [comment]
Ok, thank you!

I just took a look again and I guess I finally got what's wrong: there seems to be typo in clang.cr (see https://github.com/ysbaddaden/clang.cr/pull/5).

With this fix the PR will pass the tests.

**Comment by olbat** [comment]
Tests are fixed so the PR is ready to be reviewed/merged.

**Comment by olbat** [comment]
Thanks!

@RX14 , @mverzilli, do you think it's ready to be merged/it can be merged?

**Comment by RX14** [comment]
I don't know enough to review this.

If @ysbaddaden thinks it's okay, he can merge it right now.

**Comment by olbat** [comment]
Okay, thank you for your answer!

**Comment by olbat** [comment]
I believe it might be a good idea to centralize the effort of maintaining an up-to-date/working clang binding :-)

I'll try to find some time this week to test your binding with clang 7.

**Comment by olbat** [comment]
I added [a test](https://travis-ci.org/crystal-lang/crystal_lib/jobs/440959664) for LLVM 7.0, everything seems to be OK :)

**Comment by olbat** [comment]
Are any other changes needed?

**Comment by ysbaddaden** [comment]
No changes needed, but we're discussing to move clang.cr to the crystal-lang organization :)

**Comment by ysbaddaden** [comment]
I just did the transfer: https://github.com/crystal-lang/clang.cr

**Comment by olbat** [comment]
Okay, so I should maybe modify the shards.yml and shards.lock files accordingly?

**Comment by bcardiff** [comment]
If you can @olbat , yes please :-)

**Comment by olbat** [comment]
@bcardiff done!

**Comment by bcardiff** [comment]
Thanks @olbat !

**Pull request merged**
